<?php echo Wo_LoadPage('welcome/welcome-header');?>
<div class="wrapper">
	<div class="login forgot_pass fadeInUp animated animated_5">
		<form id="forgot-form" class="fadeInUp animated animated_9" method="post">
			<p class="title"><?php echo $wo['lang']['forgot_your_password']; ?></p>
			<div class="errors"></div>
			<input name="recoveremail" id="recoveremail" type="text" placeholder="<?php echo $wo['lang']['email'];?>" autofocus/>
			<div class="login_signup_combo">
				<div class="signup__">
					<a class="dec" href="<?php echo $wo['config']['site_url'];?>"><?php echo $wo['lang']['login']?></a>
				</div>
				<div class="login__">
					<svg class="spinner" viewBox="0 0 66 66" xmlns="http://www.w3.org/2000/svg"><circle class="spinner__path" fill="none" stroke-width="7" stroke-linecap="round" cx="33" cy="33" r="29"></circle></svg>
					<button type="submit" class="btn btn-main"><?php echo $wo['lang']['recover_password']?></button>
				</div>
			</div>
		</form>
	</div>
</div>
<div class="container"><?php echo Wo_LoadPage('footer/welcome');?></div>

<script>
var working = false;
var $this = $('#forgot-form');
var $state = $this.find('.errors');
$(function() {
  Wo_SetTimer();
  $this.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=recover',
    beforeSend: function() {
		working = true;
		$this.find('button').attr("disabled", true);
		$this.find('.spinner').addClass("show");
    },
    success: function(data) {
      if (data.status == 200) {
        $state.addClass('success');
        $state.html('<?php echo $wo['lang']['email_sent'] ?>');
		$this.find('.spinner').removeClass("show");
      } else {
		$this.find('button').attr("disabled", false);
		$this.find('.spinner').removeClass("show");
        $state.html(data.errors);
      }
      working = false;
    }
  });
});
</script>