<div id="wo_sidebar_users">
	<div class="avatar <?php echo Wo_RightToLeft('pull-left');?>">
		<img src="<?php echo $wo['UsersList']['avatar'];?>" alt="<?php echo $wo['UsersList']['name']; ?> Profile Picture"/>
	</div>
     <span class="user-popover" data-id="<?php echo $wo['UsersList']['id'];?>" data-type="<?php echo $wo['UsersList']['type'];?>">
    <a href="<?php echo $wo['UsersList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['username']?>" class="wo_user_link_name">
        <span class="user-name">
            <?php echo $wo['UsersList']['name']; ?>
        </span>
    </a>
    </span>
	
	<div class="wo_user_username_cont">
   <div class="user-username">
        @<?php echo $wo['UsersList']['username']; ?>
    </div>
	</div>
	
    <!--<?php if($wo['config']['user_lastseen'] == 1 && $wo['UsersList']['showlastseen'] != 0) { ?>
    <div class="user-lastseen">
        <?php echo Wo_UserStatus($wo['UsersList']['user_id'],$wo['UsersList']['lastseen']); ?>
    </div>
    <?php } ?>-->
    <div class="user-follow-btn">
        <div class="user-follow-button">
            <?php echo Wo_GetFollowButton($wo['UsersList']['user_id']);?>
        </div>
    </div>
</div>