<?php
$user_id            = $wo['user']['user_id'];
$wo['is_admin']     = Wo_IsAdmin();
$wo['is_moderoter'] = Wo_IsModerator();
$wo['setting']['admin'] = false;
if (isset($_GET['user']) && !empty($_GET['user']) && ($wo['is_admin'] === true || $wo['is_moderoter'] === true)) {
    if (Wo_UserExists($_GET['user']) === false) {
        header("Location: " . $wo['config']['site_url']);
        exit();
    }
    $user_id                = Wo_UserIdFromUsername($_GET['user']);
    $wo['setting']['admin'] = true;
}
$wo['setting'] = Wo_UserData($user_id);
$wo['setting']['fileds'] = Wo_UserFieldsData($user_id);
$wo['setting_page'] = 'general-setting';
$pages_array = array(
   'general-setting',
   'profile-setting',
   'privacy-setting',
   'change-password-setting',
   'social-links',
   'design-setting',
   'avatar-setting',
   'email-setting',
   'verification',
   'blocked-users',
);
if ($wo['setting']['user_id'] == $wo['user']['user_id']) {
  $pages_array = array(
   'general-setting',
   'profile-setting',
   'privacy-setting',
   'change-password-setting',
   'social-links',
   'delete-account',
   'design-setting',
   'avatar-setting',
   'email-setting',
   'verification',
   'blocked-users',
   );
}
if ($wo['config']['affiliate_system'] == 1) {
  $pages_array[] = 'affiliates';
  $pages_array[] = 'payments';
}
if (!empty($_GET['page'])) {
   if (in_array($_GET['page'], $pages_array)) {
      $wo['setting_page'] = $_GET['page'];
   }
}
$wo['user_setting'] = '';
if (!empty($_GET['user'])) {
    $wo['user_setting'] = 'user=' . $_GET['user']. '&';
}
?>
<style>@media (max-width: 600px){.wo_setting_sidebar ul {background: <?php echo $wo['config']['btn_background_color'];?>;}}
<?php if($wo['language_type'] == 'rtl') { ?>
.wo_setting_sidebar{left: 10px;right: auto;}
.wo_setting_showpage {padding-right: 0px;padding-left: 45px;}
.wo_settings_page{padding: 15px 15px 15px 55px;}
.wo_settings_page .last-sett-btn {margin-right: -15px;margin-left: -55px;}
@media (max-width: 600px){
.wo_setting_sidebar {left: 0px;}
.wo_setting_showpage {padding-right: 10px;padding-left: 10px;}
.wo_settings_page{padding: 15px;}
.wo_settings_page .last-sett-btn {margin-left: -15px;}
}
<?php } ?>
</style>
<div class="page-margin">
	<div class="row setting-panel" style="position:relative;">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-10 singlecol wo_setting_showpage"><?php echo Wo_LoadPage("setting/" . $wo['setting_page']); ?></div>
		<div class="wo_setting_sidebar"><?php echo Wo_LoadPage('setting/user-setting-sidebar');?></div>
	</div>
</div>