<div class="page-margin">
   <div class="row">
      <div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
      <div class="col-md-7 middlecol">
         <?php if ($wo['config']['user_status'] == 1) { ?>
         <div class="user-status-home">
           <ul class="status-list">
           <li>
            <div class="user-avatar">
              <a href="<?php echo Wo_SeoLink('index.php?link1=create-status'); ?>"><img src="<?php echo $wo['user']['avatar'];?>"></a>
            </div>  
            <div class="plus" onclick="window.location.href='<?php echo Wo_SeoLink('index.php?link1=create-status'); ?>'"><i class="fa fa-plus-circle"></i></div>
          </li>
           <?php
           if ($wo['config']['user_status'] == 1) {
              $get_user_status = Wo_GetFriendsStatus(array('limit' => 8));
              if (!empty($get_user_status)) {
                 ?>
                 <?php
                 foreach ($get_user_status as $key => $wo['user_status']) {
                    echo Wo_LoadPage('home/user-status');
                 }
              } 
              if (Wo_CountStories() > 8) {
                ?>
                <div class="time pull-right view-more-stories" title="<?php echo $wo['lang']['see_all'] ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=more-status'); ?>"><i class="fa fa-bars"></i></a></div><div class="clear"></div>
                <?php
              }
           } 
           ?>
           </ul>
         </div>
         <?php 
        }
         if (Wo_IsThereAnnouncement() === true) { 
           $announcement = Wo_GetHomeAnnouncements();
         ?>
         <div class="home-announcement">
            <div class="alert alert-success" style="background-color: white;">
               <span class="close announcements-option" data-toggle="tooltip" onclick="Wo_ViewAnnouncement(<?php echo $announcement['id']; ?>);" title="<?php echo $wo['lang']['hide'];?>">
               <i class="fa fa-remove"></i>
               </span>
               <?php echo $announcement['text']; ?>
            </div>
            <!-- .alert .alert-success -->
         </div>
         <!-- .home-announcement -->
         <?php
         } 
         if($wo['loggedin'] == true) {
            echo Wo_LoadPage('story/publisher-box');
         } 
        
         if ($wo['config']['order_posts_by'] == 0) {
        ?>
        <div class="order-by"> 
          <div class="dropdown">
             <?php echo $wo['lang']['store_posts_by'] ?>: <a class="dropdown-toggle" type="button" data-toggle="dropdown">
             <span class="order-text"><?php echo ($wo['user']['order_posts_by'] == 0) ? $wo['lang']['all'] : $wo['lang']['people_i_follow']; ?></span>
             <span class="caret"></span></a>
             <ul class="dropdown-menu">
               <li><a href="#" onclick="Wo_StorePosts(0);"><?php echo $wo['lang']['all'] ?></a></li>
               <li><a href="#" onclick="Wo_StorePosts(1);"><?php echo $wo['lang']['people_i_follow'] ?></a></li>
             </ul>
           </div>
        </div>
        <?php } ?>
		
		<?php if ($wo['page'] == 'home') { ?>
        <ul class="list-group filterby" id="filterby-post">
            <li class="list-group-item hidden" contenteditable="false">Filter by</li>
            <li class="list-group-item avtive filter-by-li" onclick="Wo_FilterPostBy('all');" dir="auto" style="color: #333333;"><span></span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color: #333333;"><line x1="8" y1="6" x2="21" y2="6"></line><line x1="8" y1="12" x2="21" y2="12"></line><line x1="8" y1="18" x2="21" y2="18"></line><line x1="3" y1="6" x2="3" y2="6"></line><line x1="3" y1="12" x2="3" y2="12"></line><line x1="3" y1="18" x2="3" y2="18"></line></svg><?php echo $wo['lang']['all']; ?></li>
            <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('text');" dir="auto" style="color: grey;"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color: grey;"><polyline points="4 7 4 4 20 4 20 7"></polyline><line x1="9" y1="20" x2="15" y2="20"></line><line x1="12" y1="4" x2="12" y2="20"></line></svg></li>
            <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('photos');" dir="auto" style="color: #4caf50;"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color: #4caf50;"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><circle cx="8.5" cy="8.5" r="1.5"></circle><polyline points="21 15 16 10 5 21"></polyline></svg></li>
            <li class="list-group-item filter-by-li"  onclick="Wo_FilterPostBy('video');" dir="auto" style="color: #2396f3;"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color: #2396f3;"><polygon points="23 7 16 12 23 17 23 7"></polygon><rect x="1" y="5" width="15" height="14" rx="2" ry="2"></rect></svg></li>
            <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('music');" dir="auto" style="color: #cc8317;"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color: #cc8317;"><path d="M9 17H5a2 2 0 0 0-2 2 2 2 0 0 0 2 2h2a2 2 0 0 0 2-2zm12-2h-4a2 2 0 0 0-2 2 2 2 0 0 0 2 2h2a2 2 0 0 0 2-2z"></path><polyline points="9 17 9 5 21 3 21 15"></polyline></svg></li>
            <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('files');" dir="auto" style="color: #6b376b;"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color: #6b376b;"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg></li>
            <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('maps');" dir="auto" style="color: #c12056;"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color: #c12056;"><polygon points="1 6 1 22 8 18 16 22 23 18 23 2 16 6 8 2 1 6"></polygon><line x1="8" y1="2" x2="8" y2="18"></line><line x1="16" y1="6" x2="16" y2="22"></line></svg></li>
        </ul>
        <?php } ?>
		
        <div class="btn btn-default btn-active posts-count" onclick="Wo_GetNewPosts();"></div>
        <div class="posts_load">
			<div class="wo_loading_post">
				<div class="wo_loading_post_child"></div>
			</div>
        </div>
         <!-- #posts -->
      </div>
      <!-- .col-md-8 -->
      <?php echo Wo_LoadPage('sidebar/content');?>
   </div>
   <!-- .row -->
</div>
<!-- .page-margin -->

<?php 
if ($wo['user']['social_login'] == 1) { 
  echo Wo_LoadPage('modals/create-password');
} 
?>
<script type="text/javascript">
$(function() {
    setTimeout(loadposts, 100);
});
function loadposts() {
  $.get(Wo_Ajax_Requests_File() + '?f=load_posts', function(data) {
    $('.posts_load').html(data);
  });
}
  <?php if ($wo['user']['social_login'] == 1) { ?>
  $(window).on("load", function (e) {
       $('#create-password').modal('show');
    });
  $(function() {
    var create_password_container = $('#create-password');
    $('form.create-password').ajaxForm({
      url: Wo_Ajax_Requests_File() + '?f=update_new_logged_user_details',
      beforeSend: function() {
        Wo_progressIconLoader($('form.create-password').find('button'));
      },
      success: function(data) {
        if (data.status == 200) {
          create_password_container.find('.error-container').html("<div class='alert alert-success'>" + data.message + "</div>");
           $('#update-username').attr('href', data.url);
           setTimeout(function() {
            $('#create-password').modal('hide');
           }, 1500);
        } else {
          var errors = data.errors.join("<br>");
          create_password_container.find('.error-container').html("<div class='alert alert-danger'>" + errors + "</div>");
        }
        Wo_progressIconLoader($('form.create-password').find('button'));
      }
    });
  });

<?php } ?>

function Wo_StorePosts(type) {
  if (type > 1) {
     return false;
  }
  if (type == 0) {
    $('.order-text').text('<?php echo $wo['lang']['all'] ?>');
  } else {
    $('.order-text').text('<?php echo $wo['lang']['people_i_follow'] ?>');
  }
  $('.posts_load').html('<div class="wo_loading_post"><div class="wo_loading_post_child"></div></div>');
  $.get(Wo_Ajax_Requests_File() + '?f=update_order_by', {type:type}, function (data) {
    if (data.status == 200) {
      loadposts();
    }
  });
}

function Wo_ViewAnnouncement(id) {
    var announcement_container = $('.home-announcement');
    $.get(Wo_Ajax_Requests_File() + '?f=update_announcement_views', {id:id}, function (data) {
      if (data.status == 200) {
          announcement_container.slideUp(200, function () {
            $(this).remove();
          });
      }
    });
}
</script>