<?php
$IsOwner       = Wo_IsOnwer($wo['user_profile']['user_id']);
$IsOwnerUser   = Wo_IsOnwerUser($wo['user_profile']['user_id']);

if ($wo['loggedin'] && $IsOwnerUser) {
   $wo['pr_complition'] = Wo_ProfileCompletion();
}
?>
<div class="row page-margin profile" data-page="timeline" data-id="<?php echo $wo['user_profile']['user_id'];?>">

<div class="cardheader user-cover protopcov profiletopcoversize">
                    <?php if($IsOwner === true) { ?>
                    <form action="#" method="post" class="profile-cover-changer">
                        <div class="input-group when-notedit">
                            <span class="input-group-btn">
                                <span class="btn btn-upload-image btn-file">
                                    <i class="fa fa-camera"></i>
                                    <input type="file" name="cover" accept="image/*" onchange="Wo_UpdateProfileCover();">
                                </span>
                            </span>
                        </div>
                        <div class="input-group">
                            <span class="input-group-btn when-notedit">
                                <span class="btn btn-upload-image btn-file">
                                    <i class="fa fa-pencil" data-icon="pencil" onclick="Wo_StartRepositioner();"></i>

                                </span>
                            </span>
                        </div>
                        <div class="input-group when-edit" style="display: none;">
                            <span class="input-group-btn">
                                <span class="btn btn-upload-image btn-file">
                                    <i class="fa fa-check" data-icon="pencil" onclick="Wo_SubmitRepositioner();"></i>
                                </span>
                            </span>
                        </div>
                        <div class="input-group when-edit" style="display: none;">
                            <span class="input-group-btn">
                                <span class="btn btn-upload-image btn-file">
                                    <i class="fa fa-times" data-icon="pencil" onclick="Wo_StopRepositioner();"></i>
                                </span>
                            </span>
                        </div>
                        <input type="hidden" name="user_id" value="<?php echo $wo['user_profile']['user_id'];?>">
                    </form>
                    <form class="cover-position-form hidden" method="post">
                        <input class="cover-position" name="pos" value="0" type="hidden">
                        <input class="image_type" name="image_type" value="0" type="hidden">
                        <input name="cover_image" id="cover-input-image" value="<?php echo $wo['user_profile']['cover_org']?>" type="hidden">
                        <input name="real_image" id="full-input-image" value="<?php echo Wo_GetMedia($wo['user_profile']['cover_full']); ?>" type="hidden">
                    </form>
                    <?php } ?>
                    <div class="user-cover-uploading-container"></div>
                    <div class="user-cover-uploading-progress">
                        <i class="fa fa-spinner fa-spin progress-icon" data-icon="spin"></i>
                    </div>
                    <div class="user-cover-reposition-container">
                        <div class="user-cover-reposition-w user-cover-pc">
                            <img id="cover-image" src="<?php echo $wo['user_profile']['cover']?>" alt="<?php echo $wo['user_profile']['name']?> Cover Image" onclick="Wo_OpenProfileCover('<?php echo $wo['user_profile']['cover_org']?>');" class="pointer" style="width: 100%;height: 320px;"/>
                        </div>
						
						<div class="user-cover-mobile">
                            <i id="cover-image" style="background: #fff url(<?php echo $wo['user_profile']['cover_full']?>) no-repeat center;background-size: cover;background-position: 50% 50%;"></i>
                        </div>
						
                        <div class="user-reposition-container" style="height: 320px;">
                            <img id="full-image" src="<?php echo Wo_GetMedia($wo['user_profile']['cover_full'])?>" alt="User Image">
                            <div class="user-reposition-dragable-container" align="center"><i class="fa fa-bars"></i>
                            <?php echo $wo['lang']['drag_to_re']; ?></div>
                            <div class="user-cover-uploading-container user-repositioning-icons-container1"></div>
                            <div class="user-cover-uploading-progress user-repositioning-icons-container"></div>
                        </div>
                    </div>
                </div>
					<div class="text-shadow problackback"></div>
				
				<div class="profile-container name-cont-mobile" style="margin-top: 120px;">
            <div class="profile-top-line"></div>
            <div class="card hovercard">
                
				
				<div class="propicname">
                <div class="user-avatar flip main-profile-user" id="profile-pic-mobile" style="position: relative;top: inherit;bottom: 0px;">
                    <div class="user-avatar-uploading-container" style="border-radius: 50%;z-index: 99;">
                        <div class="user-avatar-uploading-progress">
                            <i class="fa fa-spinner fa-spin fa-spin progress-icon" data-icon="spin"></i>
                        </div>
                    </div>
                    <img id="updateImage-<?php echo $wo['user_profile']['user_id']?>" class="pointer timelineuserpropic" alt="<?php echo $wo['user_profile']['name']?> Profile Picture" src="<?php echo $wo['user_profile']['avatar']?>" onclick="Wo_OpenProfilePicture('<?php echo $wo['user_profile']['avatar_org']?>');"/>
                    <?php if($IsOwner === true) { ?>
                    <form action="#" method="post" class="profile-avatar-changer" id="propic-form-mobile" style="text-align: center;display: block;">
                        <div class="input-group">
                            <span class="input-group-btn">
                            <span class="btn btn-upload-image btn-file" id="upload-propic-mobile">
                            <i class="zmdi zmdi-camera"></i>
                            <input type="file" name="avatar" accept="image/x-png, image/jpeg" onchange="Wo_UpdateProfileAvatar();">
                            </span>
                            </span>
                        </div>
                        <input type="hidden" name="user_id" id="user-id" value="<?php echo $wo['user_profile']['user_id'];?>">
                    </form>
                    <?php } ?>
                </div>
                
                <div class="infoz">
                    <div class="title main-profile-user-title" id="timelineusernam">
                        <a class="pronameblack" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username'];?>" style="color: #fff;">
                        <?php echo $wo['user_profile']['name']; ?>
                        </a>
                        <?php if($wo['user_profile']['verified'] == 1) {   ?>
                        <i class="zmdi zmdi-badge-check verified-color" data-toggle="tooltip" data-placement="bottom" title="<?php echo $wo['lang']['verified_user'];?>"></i>
                        <?php } ?>
						
						<br>
						
						<div class="profile-social-link-mobile">
						<?php if($wo['user_profile']['website']) {   ?>
						<a href="<?php echo $wo['user_profile']['website']?>" target="_blank" style="font-size: 12px;padding: 0px 5px;">
						<span class="zmdi-hc-stack zmdi-hc-lg" style="width: 1.5em;height: 1.5em;line-height: 1.5em;">
							<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #91959d;font-size: 1.5em;"></i>
							<i class="zmdi zmdi-link zmdi-hc-stack-1x zmdi-hc-inverse"></i>
						</span>
						</a>
						<a href="<?php echo $wo['user_profile']['website']?>" target="_blank" style="font-size: 12px;font-family: verdana;border-bottom: 1px solid #ddd;padding: 2px 5px;">
						<?php echo $wo['user_profile']['website']?>
						</a>
						<?php } else { ?>					
						<?php if(!empty($wo['user_profile']['facebook']) || !empty($wo['user_profile']['twitter']) || !empty($wo['user_profile']['google']) || !empty($wo['user_profile']['linkedin']) || !empty($wo['user_profile']['vk']) || !empty($wo['user_profile']['youtube'])) { ?>
						<ul class="list-group" style="border: 0px;">
							<li class="list-group-item hidden" contenteditable="false"></li>
							<li class="list-group-item text-center" style="padding: 15px 10px;">
							<div class="bottom">
								<?php  if(!empty($wo['user_profile']['youtube'])) {  ?>
								<a class="social-btn" href="https://www.youtube.com/<?php echo $wo['user_profile']['youtube']?>" target="_blank">
									<i class="fa fa-youtube"></i>
								</a>
								<?php } if(!empty($wo['user_profile']['twitter'])) {  ?>
								<a class="social-btn" href="https://twitter.com/<?php echo $wo['user_profile']['twitter']?>" target="_blank">
									<i class="fa fa-twitter"></i>
								</a>
								<?php }  if(!empty($wo['user_profile']['google'])) {  ?>
								<a class="social-btn" rel="publisher" href="https://plus.google.com/<?php echo $wo['user_profile']['google']?>" target="_blank">
									<i class="fa fa-google-plus"></i>
								</a>
								<?php }  if(!empty($wo['user_profile']['facebook'])) {  ?>
								<a class="social-btn" rel="publisher" href="https://www.facebook.com/<?php echo $wo['user_profile']['facebook']?>" target="_blank">
									<i class="fa fa-facebook"></i>
								</a>
								<?php }  if(!empty($wo['user_profile']['linkedin'])) {  ?>
								<a class="social-btn" rel="publisher" href="https://www.linkedin.com/profile/view?id=<?php echo $wo['user_profile']['linkedin']?>" target="_blank">
									<i class="fa fa-linkedin"></i>
								</a>
								<?php } ?>
								<?php  if(!empty($wo['user_profile']['vk'])) {  ?>
								<a class="social-btn" rel="publisher" href="https://vk.com/<?php echo $wo['user_profile']['vk'];?>" target="_blank">
									<i class="fa fa-vk"></i>
								</a>
								<?php } ?>
								<?php  if(!empty($wo['user_profile']['instagram'])) {  ?>
								<a class="social-btn" rel="publisher" href="https://instagram.com/<?php echo $wo['user_profile']['instagram'];?>" target="_blank">
									<i class="fa fa-instagram"></i>
								</a>
								<?php } ?>
							</div>
							</li>
						</ul>
						<?php } ?>
						<?php } ?>
						</div>
						
                    </div>
                    <div class="main-profile-user-option options-buttons prouseroptions">
                        <span class="profile-message-btn">
                        <?php echo Wo_GetMessageButton($wo['user_profile']['user_id']);?>
                        </span>
                        <span class="user-follow-button">
                        <?php echo Wo_GetFollowButton($wo['user_profile']['user_id']);?>
                        </span>
						<?php if($IsOwner === true) { ?>
						<span class="wabe btn btn-default" style="padding: 0px;margin-left: 10px;">
                         <a href="<?php echo Wo_SeoLink('index.php?link1=setting&user=' . $wo['user_profile']['username'] . '&page=general-setting') ?>" data-ajax="?link1=setting&user=<?php echo $wo['user_profile']['username'] . '&page=general-setting'; ?>" style="padding: 5.5px 12px;margin-left: 0px;height:30px"><i class="zmdi zmdi-settings" style="font-size: 15px;margin: -2px 3px 0px 0px;"></i><?php echo $wo['lang']['edit_user'];?></a>
						</span>
						<?php } ?>
                    </div>
                </div>
				</div>
				
				<div id="profilenav">
		<ul class="cusscrolz">
		
		<li>
		<a class="groupmenulist" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username'];?>">
		<span><?php if($wo['language'] == "english") { ?>Timeline<?php } ?>
				<?php if($wo['language'] == "arabic") { ?>الجدول الزمني<?php } ?>
				<?php if($wo['language'] == "dutch") { ?>Tijdlijn<?php } ?>
				<?php if($wo['language'] == "french") { ?>Chronologie<?php } ?>
				<?php if($wo['language'] == "german") { ?>Zeitleiste<?php } ?>
				<?php if($wo['language'] == "italian") { ?>Sequenza temporale<?php } ?>
				<?php if($wo['language'] == "portuguese") { ?>Cronograma<?php } ?>
				<?php if($wo['language'] == "russian") { ?>График<?php } ?>
				<?php if($wo['language'] == "spanish") { ?>Cronología<?php } ?>
				<?php if($wo['language'] == "turkish") { ?>Zaman çizelgesi<?php } ?></span></a></li>
		
		<!--<li>
		<a class="groupmenulist" href="<?php echo Wo_SeoLink('index.php?link1=albums&user=' . $wo['user_profile']['username']);?>" data-ajax="?link1=albums&user=<?php echo $wo['user_profile']['username'];?>">
		<span><?php echo $wo['lang']['albums'];?></span></a></li>-->
		
		<li>
		<a class="groupmenulist" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=groups');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=groups">
		<span><?php echo $wo['lang']['groups'];?></span></a></li>
		
		<li>
		<a class="groupmenulist" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=likes');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=likes">
		<span><?php echo $wo['lang']['likes'];?></span></a></li>
		
		<?php if ($wo['config']['connectivitySystem'] == 1) {?>
			<li>
		<a class="groupmenulist" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=followers');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=followers">
		<span><?php echo $wo['lang']['friends_btn'];?></span></a></li>	
		<?php } ?>
		
		<?php if ($wo['config']['connectivitySystem'] == 0) {?>
		<li>
		<a class="groupmenulist" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=following');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=following">
		<span><?php echo $wo['lang']['following'];?></span></a></li>
		
		<li>
		<a class="groupmenulist" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=followers');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=followers">
		<span><?php echo $wo['lang']['followers'];?></span></a></li>
		<?php } ?>
		</ul>
		</div>
		
		
				<div id="profilenav-mobile">
		<ul class="cusscrolz">
		
		<li>
		<a class="groupmenulist" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username'];?>">
		<span><b><?php echo $wo['user_profile']['details']['post_count'];?></b></span>
		<span class="split-link"><?php echo $wo['lang']['posts']; ?></span>
		</a></li>
		
		<?php if ($wo['config']['connectivitySystem'] == 1) {?>
		<li>
		<a class="groupmenulist" href="<?php echo Wo_SeoLink('index.php?link1=albums&user=' . $wo['user_profile']['username']);?>" data-ajax="?link1=albums&user=<?php echo $wo['user_profile']['username'];?>">
		<span><b><?php echo $wo['user_profile']['details']['album_count'];?></b></span>
		<span class="split-link"><?php echo $wo['lang']['albums'];?></span>
		</a></li>
		
		<li>
		<a class="groupmenulist" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=followers');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=followers">
		<span><b><?php echo $wo['user_profile']['details']['following_count'];?></b></span>
		<span class="split-link"><?php echo $wo['lang']['friends_btn'];?></span>
		</a></li>	
		<?php } ?>
		
		<?php if ($wo['config']['connectivitySystem'] == 0) {?>
		<li>
		<a class="groupmenulist" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=following');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=following">
		<span><b><?php echo $wo['user_profile']['details']['following_count'];?></b></span>
		<span class="split-link"><?php echo $wo['lang']['following'];?></span>
		</a></li>
		
		<li>
		<a class="groupmenulist" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=followers');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=followers">
		<span><b><?php echo $wo['user_profile']['details']['followers_count'];?></b></span>
		<span class="split-link"><?php echo $wo['lang']['followers'];?></span>
		</a></li>
		<?php } ?>
		
		</ul>
		</div>
		
		
				
            </div>
        </div>
    <div class="col-md-8">
        <?php
            if (isset($_GET['type'])) {
              if ($_GET['type'] == 'following') {
            ?>
        <div class="list-group profile-lists">
         <div class="list-group-item">
         <i class="fa fa-fw fa-users"></i><?php echo $wo['lang']['following'];?>
         <span class="pull-right">
            <a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=family_list');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=family_list">
                <?php echo $wo['lang']['family_members']; ?>
             </a> 
         </span>
         </div>
            <div id="following-list" class="setting-well">
                <?php
                    if ($wo['user_profile']['details']['following_count'] == 0) {
                        echo '<h5 class="search-filter-center-text">' . $wo['lang']['not_following'] . '</h5>';
                    } else {
                        foreach (Wo_GetFollowing($wo['user_profile']['user_id'],'profile', 100) as $wo['UsersList']) {
                            echo Wo_LoadPage('timeline/follow-list');
                        }
                    }
                    ?>
            </div>
            <div class="clear"></div>
        </div>
        <?php if ($wo['user_profile']['details']['following_count'] > 10) { ?>
        <div class="load-more">
            <button class="btn btn-default text-center pointer" onclick="Wo_GetMoreFollowing(<?php echo $wo['user_profile']['user_id'];?>);">
            <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> <?php echo $wo['lang']['load_more_users']; ?></button>
        </div>
        <?php } ?>
        <?php } else if ($_GET['type'] == 'followers') { ?>
         <div class="list-group profile-lists">
         <div class="list-group-item"><i class="fa fa-fw fa-users"></i>  

         <?php 
         if ($wo['config']['connectivitySystem'] == 1) {
            echo $wo['lang']['friends_btn'];
         } else {
            echo $wo['lang']['followers'];
         }
         ?> 
         <span class="pull-right">
            <a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=family_list');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=family_list">
                <?php echo $wo['lang']['family_members']; ?>
             </a> 
         </span>
         
         </div>
            <div id="followers-list" class="setting-well">
                <?php
                    if ($wo['user_profile']['details']['followers_count'] == 0) {
                        if ($wo['config']['connectivitySystem'] == 1) {
                            echo '<h5 class="search-filter-center-text">' . $wo['lang']['no_friends'] . '</h5>';
                        } else {
                            echo '<h5 class="search-filter-center-text">' . $wo['lang']['no_followers'] . '</h5>';
                        }
                    } else {
                        foreach (Wo_GetFollowers($wo['user_profile']['user_id'],'profile',100) as $wo['UsersList']) {
                          echo Wo_LoadPage('timeline/follow-list');
                        } 
                    }
                    ?>
            </div>
            <div class="clear"></div>
        </div>
        <?php if ($wo['user_profile']['details']['followers_count'] > 10) {  ?>
        <div class="load-more">
            <button class="btn btn-default text-center pointer" onclick="Wo_GetMoreFollowers(<?php echo $wo['user_profile']['user_id'];?>);">
            <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> <?php echo $wo['lang']['load_more_users']; ?></button>
        </div>
        <?php } ?>
        <?php } else if ($_GET['type'] == 'likes') { ?>
        <div class="list-group profile-lists">
         <div class="list-group-item"><i class="fa fa-fw fa-thumbs-up"></i> <?php echo $wo['lang']['likes'];?></div>
            <div id="likes-list" class="setting-well">
                <?php
                    if (Wo_CountUserLikes($wo['user_profile']['user_id']) == 0) {
                        echo '<h5 class="search-filter-center-text">' . $wo['lang']['no_likes'] . '</h5>';
                    } else {
                        foreach (Wo_GetLikes($wo['user_profile']['user_id'],'profile',100) as $wo['PageList']) {
                          echo Wo_LoadPage('timeline/likes-list');
                        } 
                    }
                    ?>
            </div>
            <div class="clear"></div>
        </div>
        <?php if (Wo_CountUserLikes($wo['user_profile']['user_id']) > 10) {  ?>
        <div class="load-more">
            <button class="btn btn-default text-center pointer" onclick="Wo_GetMoreUserLikes(<?php echo $wo['user_profile']['user_id'];?>);">
            <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> <?php echo $wo['lang']['load_more_pages'];?></button>
        </div>
        <?php } ?>
        <?php } else if ($_GET['type'] == 'groups') { ?>
        <div class="list-group profile-lists">
         <div class="list-group-item"><i class="fa fa-fw fa-users"></i> <?php echo $wo['lang']['groups'];?></div>
            <div id="groups-list" class="setting-well">
                <?php
                    if (Wo_CountUserGroups($wo['user_profile']['user_id']) == 0) {
                        echo '<h5 class="search-filter-center-text">' . $wo['lang']['no_groups'] . '</h5>';
                    } else {
                        foreach (Wo_GetUsersGroups($wo['user_profile']['user_id'], 5000) as $wo['GroupList']) {
                          echo Wo_LoadPage('timeline/groups-list');
                        } 
                    }
                    ?>
            </div>
            <div class="clear"></div>
        </div>
        <?php } else if ($_GET['type'] == 'family_list') { ?>
        <div class="list-group profile-lists">
         <div class="list-group-item"><i class="fa fa-fw fa-users"></i> <?php echo $wo['lang']['family_members']; ?>
             <?php if ($wo['user_profile']['user_id'] == $wo['user']['id']): ?>
                 <span class="pull-right">
                     <a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=requests');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=requests">
                     <?php echo $wo['lang']['requests']; ?>
                     </a>
                 </span>
             <?php endif; ?>
         </div>
            <div id="family-members-list" class="setting-well">
                <?php 
                     $family = Wo_GetFamaly($wo['user_profile']['user_id'],false,1);
                     $i      = 0;
                     if (count($family) > 0) {
                        foreach ($family as $wo['UsersList']) {
                            if ($wo['UsersList']['type'] == 'family') {
                                echo Wo_LoadPage('timeline/family-list');
                                $i++;
                            }
                        }
                     }

                     if($i < 1){
                        echo '<h5 class="search-filter-center-text"> ' . $wo['lang']['no_members_found'] . '</h5>';
                     }
                     

                ?>
            </div>
            <div class="clear"></div>
        </div>
        <?php } else if ($_GET['type'] == 'requests' && $wo['user_profile']['user_id'] == $wo['user']['id']) { ?>
        <div class="list-group profile-lists">
         <div class="list-group-item">
         <i class="fa fa-fw fa-users"></i> 
         <?php echo $wo['lang']['requests']; ?>
         <span class="pull-right">
             <i class="fa fa-chevron-circle-left" aria-hidden="true"></i> 
             <a  href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=family_list');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=family_list">
                
                 <?php echo $wo['lang']['family_members']; ?>
             </a> 
         </span>
         </div>
            <div id="family-requests-list" class="setting-well">
                <?php 
                     $family = Wo_GetFamaly($wo['user_profile']['user_id'],false,0,true);
                     if (count($family) > 0) {
                        $i      = 0;
                        foreach ($family as $wo['UsersList']) {
                            if ($wo['UsersList']['type'] == 'family' || $wo['UsersList']['type'] == 'rel_ship') {
                                echo Wo_LoadPage('timeline/requests-list');
                                $i++;
                            }
                        }
                     }

                     else{
                        echo '<h5 class="search-filter-center-text"> ' . $wo['lang']['no_requests_found'] . '</h5>';
                     }
                ?>
            </div>
            <div class="clear"></div>
        </div>
        <?php } else { 
               header("Location: " . Wo_SeoLink('index.php?link1=timeline&u=' . $_GET['u'])); 
               exit(); 
            } ?>
        <?php } else { echo Wo_GetPostPublisherBox(0, $wo['user_profile']['user_id']); ?>
        <?php if ($wo['loggedin'] == true) { echo Wo_LoadPage('story/filter-by'); } ?>
        <div class="posts_load">
          <div id="posts" data-story-user="<?php echo $wo['user_profile']['user_id'];?>">
            <div class="pinned-post-container">
                <?php
                    $pinedstory = Wo_GetPinnedPost($wo['user_profile']['user_id']);
                    if (count($pinedstory) == 1) {
                        foreach ($pinedstory  as $wo['story']) {
                          echo Wo_LoadPage('story/content');
                        }
                    }
                    ?>
        </div>
            <?php
                $stories = Wo_GetPosts(array('filter_by' => 'all','publisher_id' => $wo['user_profile']['user_id'])); 
                if (count($stories) == 0 && count($pinedstory) == 0) {
                   echo Wo_LoadPage('story/profile-no-stories');
                } else {
                   foreach ($stories as $wo['story']) {
                     echo Wo_LoadPage('story/content');
                   }
                }
                ?>
        </div>
        <?php if ($wo['loggedin'] == true && count($stories) > 0) {  ?>
        <div class="load-more pointer" id="load-more-posts" onclick="Wo_GetMorePosts();">
            <span class="btn btn-default"><i class="fa fa-chevron-circle-down progress-icon" data-icon="chevron-circle-down"></i> <?php echo $wo['lang']['load_more_posts']; ?><span>
        </div>
        <?php } ?>


        </div>
             
         <?php } ?>
        <div id="load-more-filter">
            <span class="filter-by-more hidden" data-filter-by="all"></span>
        </div>
    </div>
    <div class="col-md-4 cussidefix">
			<!-- Profile Percentage System -->

        <?php if ($IsOwnerUser === true && array_sum($wo['pr_complition']) < 100): ?>
            <?php echo Wo_LoadPage('timeline/profile-completion'); ?>
        <?php endif; ?>
	
             <?php if ($wo['config']['user_status'] == 1 && Wo_CountUserStatus($wo['user_profile']['id']) > 0): ?>
			 <ul class="list-group">
			 <li class="list-group-item hidden"></li>
                <li class="list-group-item pointer" onclick="Wo_LoadStory('prof', $('[data-page=timeline]').attr('data-id'));" style="font-weight: bold;">
                    <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
						<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #FF9800;"></i>
						<i class="zmdi zmdi-chart-donut zmdi-hc-stack-1x" style="color: white;"></i>
					</span>
                    <?php echo $wo['lang']['story']; ?>
                    
                </li>
				</ul>
            <?php endif; ?>
            
	
        <ul class="list-group">
            <li class="list-group-item text-muted hidden" contenteditable="false">
                <?php echo $wo['lang']['details']; ?>
            </li>
			<?php if($wo['loggedin'] == true) {  ?>
			<li class="list-group-item" style="padding: 10px;">
                <input type="text" class="form-control search-for-posts" onkeyup="Wo_SearchForPosts(this.value);" placeholder="<?php echo $wo['lang']['search_for_posts']; ?>" style="border-radius: 16px;">
            </li>
			<?php } ?>	
            <?php if (Wo_IsUserPro($wo['user_profile']['is_pro']) === true) { 
            $user_pro_type = Wo_GetUserProType($wo['user_profile']['pro_type']);
            ?>
            <li class="list-group-item" style="color:#fff; background-color:<?php echo $user_pro_type['color_name'];?>">
                <strong style="margin-left: 5px;"><i class="fa fa-<?php echo $user_pro_type['icon'];?> fa-fw"></i></strong>
                <?php echo $user_pro_type['type_name'];?>
            </li>
            <?php } ?>			
            <?php if($wo['config']['user_lastseen'] == 1 && $wo['user_profile']['showlastseen'] != 0 && $wo['loggedin'] == true) {  ?>
            <li class="list-group-item">
                <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
						<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #21b089;"></i>
						<i class="zmdi zmdi-eye zmdi-hc-stack-1x" style="color: white;"></i>
					</span>
                <?php echo Wo_UserStatus($wo['user_profile']['user_id'], $wo['user_profile']['lastseen'], 'profile') ?> 
            </li>
            <?php } ?>
            <li class="list-group-item">
                <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
						<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #f4a300;"></i>
						<i class="zmdi zmdi-edit zmdi-hc-stack-1x" style="color: white;"></i>
					</span>
               <?php echo Wo_CountUserPosts($wo['user_profile']['user_id']);?> <?php echo $wo['lang']['posts']; ?>
            </li>
			
            <li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
            <li class="list-group-item">
                <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
						<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #a359ce;"></i>
						<i class="zmdi zmdi-male-female zmdi-hc-stack-1x" style="color: white;"></i>
					</span>
                <?php 
                $gender = ucfirst(strtolower($wo['user_profile']['gender']));
                echo ($gender == 'Male') ? $wo['lang']['male'] : $wo['lang']['female']; 
                ?>
            </li>
            <?php if ($wo['user_profile']['birthday'] != '0000-00-00' && Wo_CanSeeBirthday($wo['user_profile']['user_id'], $wo['user_profile']['birth_privacy']) === true) {  ?>
            <li class="list-group-item">
                <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
						<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #7a8192;"></i>
						<i class="zmdi zmdi-calendar zmdi-hc-stack-1x" style="color: white;"></i>
					</span>
                <?php echo date($wo['config']['date_style'],strtotime($wo['user_profile']['birthday']));?>
                
            </li>
            <?php  }  ?>
			
            <?php if(!empty(Wo_UserRelationship($wo['user_profile']['id']))) {  ?>
            <li class="list-group-item">
                <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
						<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #d85a49;"></i>
						<i class="zmdi zmdi-favorite zmdi-hc-stack-1x" style="color: white;"></i>
					</span>
                <?php echo Wo_UserRelationship($wo['user_profile']['id']); ?>
            </li>
            <li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
            <?php } ?>
            <?php if(!empty($wo['user_profile']['working'])) {  ?>
            <li class="list-group-item">
                <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
						<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #aa7d4f;"></i>
						<i class="zmdi zmdi-case zmdi-hc-stack-1x" style="color: white;"></i>
					</span>
                <span><?php echo $wo['lang']['working_at'];?> <?php if (!empty($wo['user_profile']['working_link'])) { ?><a href="<?php echo $wo['user_profile']['working_link']; ?>" target="_blank" rel="nofollow"><?php echo $wo['user_profile']['working']; ?></a> <?php } else { echo $wo['user_profile']['working'];} ?></span>
            </li>
            <?php } ?>
            <?php if(!empty($wo['user_profile']['school'])) {  ?>
            <li class="list-group-item">
                <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
						<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #d85a49;"></i>
						<i class="zmdi zmdi-book zmdi-hc-stack-1x" style="color: white;"></i>
					</span>
                <span><?php echo $wo['lang']['studying_at'];?> <?php echo $wo['user_profile']['school']; ?></span>
            </li>
            <li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
            <?php } ?>
            
            <?php 
            $country = $wo['user_profile']['country_id'];
            if ($country > 0) {
            ?>
            <li class="list-group-item">
                <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
						<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #80acdb;"></i>
						<i class="zmdi zmdi-globe zmdi-hc-stack-1x" style="color: white;"></i>
					</span>
                <?php echo $wo['lang']['living_in'];?> 
                <?php echo $wo['countries_name'][$country];?>
            </li>
            <?php } ?>
            <?php if(!empty($wo['user_profile']['address'])) {  ?>
            <li class="list-group-item">
                <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
						<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #df342e;"></i>
						<i class="zmdi zmdi-pin zmdi-hc-stack-1x" style="color: white;"></i>
					</span>
                <span><?php echo $wo['lang']['located_in'];?> <?php echo $wo['user_profile']['address'];?></span>
                <?php if (!empty($wo['config']['google_map_api'])) { ?>
                <iframe width="100%" frameborder="0" style="border:0;margin-top: 10px;padding: 0px;" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=<?php echo $wo['user_profile']['address'];?>&language=en"></iframe>
                <?php } ?>
            </li>
            
            <?php } ?>
			
            <?php if ($wo['loggedin'] == true) { ?>
            <li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
            <?php } ?>
            <?php if($IsOwnerUser === false && $wo['loggedin'] == true) { ?>
            <li class="list-group-item">
                <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
						<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #222;"></i>
						<i class="zmdi zmdi-close zmdi-hc-stack-1x" style="color: white;"></i>
					</span>
                <span><a href="<?php echo $wo['marker'] . 'block_user=block'?>"><?php echo $wo['lang']['block_user'];?></a></span>
            </li>
            <?php } ?>
			
			
			<?php if($IsOwnerUser === false && $wo['loggedin'] == true && !Wo_IsFamilyMemberExists($wo['user']['id'],$wo['user_profile']['id'],false)) { ?>
                <li class="list-group-item" id="open_add_to_family_modal">
                    <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
						<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #2d84ca;"></i>
						<i class="zmdi zmdi-accounts zmdi-hc-stack-1x" style="color: white;"></i>
					</span>
                    <span onclick="$('#add_to_family').modal('show');"><span class="pointer"><?php echo $wo['lang']['add_to_family'];?></span></span>
                </li>
            <?php } ?>



            <?php if ($wo['loggedin'] && !Wo_IsAdmin() && $wo['user']['id'] != $wo['user_profile']['id'] && !Wo_IsAdmin($wo['user_profile']['id'])): ?>
                <?php if (!Wo_IsReportExists($wo['user_profile']['id'],'user')): ?>
                <li id="report_status" class="list-group-item pointer" onclick="$('#report_profile').modal('show');">
                    <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
						<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #dcaa19;"></i>
						<i class="zmdi zmdi-flag zmdi-hc-stack-1x" style="color: white;"></i>
					</span>
                    <span><?php echo $wo['lang']['report_user']; ?></span>
                </li>
                <?php else: ?>
                <li id="report_status" class="list-group-item pointer" onclick="Wo_ReportProfile(<?php echo $wo['user_profile']['id']; ?>,false);">
                    <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
						<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #dcaa19;"></i>
						<i class="zmdi zmdi-flag zmdi-hc-stack-1x" style="color: white;"></i>
					</span>
                    <span><?php echo $wo['lang']['unreport']; ?></span>
                </li>
                <?php endif; ?>
            <?php endif;?>
			
            <?php if(Wo_IsAdmin() || Wo_IsModerator()) { ?>
            <li class="list-group-item">
                <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
						<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #414a61;"></i>
						<i class="zmdi zmdi-settings zmdi-hc-stack-1x" style="color: white;"></i>
					</span>
                <span><a href="<?php echo Wo_SeoLink('index.php?link1=setting&user=' . $wo['user_profile']['username'] . '&page=general-setting') ?>" data-ajax="?link1=setting&user=<?php echo $wo['user_profile']['username'] . '&page=general-setting'; ?>"><?php echo $wo['lang']['edit_user'];?></a></span>
            </li>
            <?php } ?>
        </ul>
        <?php if(!empty($wo['user_profile']['website'])) {  ?>
        <ul class="list-group">
            <li class="list-group-item text-muted" contenteditable="false"><i class="zmdi zmdi-link" style="font-size: 20px;margin: -3px 5px 0px 0px;"></i> <?php echo $wo['lang']['website']; ?></li>
            <li class="list-group-item text-left">
                <i class="zmdi zmdi-chevron-right" style="font-size: 17px;margin: -1px 5px 0px 0px;"></i>
                <a href="<?php echo $wo['user_profile']['website']?>" target="_blank">
                <?php echo $wo['user_profile']['website']?>
                </a>
            </li>
        </ul>
        <?php } ?>
		
		
        <?php if(!empty($wo['user_profile']['about'])) {  ?>
        <ul class="list-group">
            <li class="list-group-item text-muted" contenteditable="false"><i class="zmdi zmdi-account-circle" style="font-size: 20px;margin: -3px 5px 0px 0px;"></i> <?php echo $wo['lang']['about']; ?></li>
            <li class="list-group-item text-left">
                <?php echo $wo['user_profile']['about']?>
            </li>
        </ul>
        <?php } ?>
        <?php if(!empty($wo['user_profile']['facebook']) || !empty($wo['user_profile']['twitter']) || !empty($wo['user_profile']['google']) || !empty($wo['user_profile']['linkedin']) || !empty($wo['user_profile']['vk']) || !empty($wo['user_profile']['youtube'])) { ?>
        <ul class="list-group">
            <li class="list-group-item text-muted" contenteditable="false">
                <i class="zmdi zmdi-share" style="font-size: 20px;margin: -3px 5px 0px 0px;"></i> <?php echo $wo['lang']['social_links']; ?>
            </li>
            <li class="list-group-item text-center" style="padding: 15px 10px;">
                <div class="bottom">
                    <?php  if(!empty($wo['user_profile']['youtube'])) {  ?>
                    <a class="btn social-btn btn-google" href="https://www.youtube.com/<?php echo $wo['user_profile']['youtube']?>" target="_blank">
                    <i class="zmdi zmdi-youtube" style="font-size: 19px;vertical-align: initial;"></i>
                    </a>
                    <?php } if(!empty($wo['user_profile']['twitter'])) {  ?>
                    <a class="btn social-btn btn-twitter" href="https://twitter.com/<?php echo $wo['user_profile']['twitter']?>" target="_blank">
                    <i class="zmdi zmdi-twitter" style="font-size: 19px;vertical-align: initial;margin-left: -2px;"></i>
                    </a>
                    <?php }  if(!empty($wo['user_profile']['google'])) {  ?>
                    <a class="btn social-btn btn-google" rel="publisher" href="https://plus.google.com/<?php echo $wo['user_profile']['google']?>" target="_blank">
                    <i class="zmdi zmdi-google-plus" style="font-size: 19px;vertical-align: initial;margin-left: -1px;"></i>
                    </a>
                    <?php }  if(!empty($wo['user_profile']['facebook'])) {  ?>
                    <a class="btn social-btn btn-facebook" rel="publisher" href="https://www.facebook.com/<?php echo $wo['user_profile']['facebook']?>" target="_blank">
                    <i class="zmdi zmdi-facebook" style="font-size: 19px;vertical-align: initial;"></i>
                    </a>
                    <?php }  if(!empty($wo['user_profile']['linkedin'])) {  ?>
                    <a class="btn social-btn btn-linkedin" rel="publisher" href="https://www.linkedin.com/profile/view?id=<?php echo $wo['user_profile']['linkedin']?>" target="_blank">
                    <i class="zmdi zmdi-linkedin" style="font-size: 19px;vertical-align: initial;margin-left: -2px;"></i>
                    </a>
                    <?php } ?>
                    <?php  if(!empty($wo['user_profile']['vk'])) {  ?>
                    <a class="btn social-btn btn-vk" rel="publisher" href="https://vk.com/<?php echo $wo['user_profile']['vk'];?>" target="_blank">
                    <i class="zmdi zmdi-vk" style="font-size: 19px;vertical-align: initial;margin-left: -4px;"></i>
                    </a>
                    <?php } ?>
                    <?php  if(!empty($wo['user_profile']['instagram'])) {  ?>
                    <a class="btn social-btn btn-instagram" rel="publisher" href="https://instagram.com/<?php echo $wo['user_profile']['instagram'];?>" target="_blank">
                    <i class="zmdi zmdi-instagram" style="font-size: 19px;vertical-align: initial;margin-left: -2px;"></i>
                    </a>
                    <?php } ?>
                </div>
            </li>
        </ul>
        <?php }
        $fields = Wo_GetProfileFields('none'); 
        if (count($fields) > 0) { ?>
        <ul class="list-group">
            <li class="list-group-item text-muted" contenteditable="false"><i class="zmdi zmdi-info" style="font-size: 20px;margin: -3px 5px 0px 0px;"></i> <?php echo $wo['lang']['more_info']; ?>
            </li>
            <?php
            foreach ($fields as $key => $wo['field']) {
                $name = $wo['field']['fid'];
                if (!empty($wo['user_profile']['fields'][$name])) {
                    echo Wo_LoadPage('timeline/custom-fields');
                }
            }
            ?>
        </ul>
        <?php } if($wo['loggedin'] == true) {  ?>
        
        <?php } ?>
        <?php 
            if ($wo['config']['connectivitySystem'] == 1) {
              echo Wo_LoadPage('timeline/friends-sidebar');
            } else {
              echo Wo_LoadPage('timeline/following-followers-sidebar');
            }
            echo Wo_LoadPage('timeline/likes-sidebar');
            echo Wo_LoadPage('timeline/groups-sidebar');
            echo Wo_LoadPage('timeline/albums-sidebar');
            ?>
        <?php 
            $sidebar_ad = Wo_GetAd('sidebar', false);
            if (!empty($sidebar_ad)) {?>
        <ul class="list-group sidebar-ad">
            <?php echo $sidebar_ad; ?>
        </ul>
        <?php } ?>
        <?php echo Wo_LoadPage('footer/sidebar-footer')?>
    </div>
</div>
<?php echo Wo_LoadPage('modals/profile-picture');?>
<?php echo Wo_LoadPage('modals/cover-image');?>
<?php if (!empty($wo['user_profile']['background_image']) && $wo['user_profile']['background_image_status'] == 1) { ?>
<style>
  body {
    background: url(<?php echo Wo_GetMedia($wo['user_profile']['background_image']); ?>) fixed;
    background-size:100% auto;
  }
</style>
<?php } ?>
<style>
body {padding-left: 0px;}
.navbar-default {padding-right: 0px;}
.social-btn {width: 12%;border-radius: 50%;}
.profiletopcoversize{padding-right: 0px;}

@media (min-width: 1500px){
.sidebar-following-users-container .sidebar-listed-user-avatar img{height: 97.5px !important;}
.sidebar-followers-users-container .sidebar-listed-user-avatar img{height: 97.5px !important;}
body {padding-left: 0px;padding-right: 260px;}
}
@media (min-width: 1200px){
body {padding-left: 0px;padding-right: 205px;}
.navbar-default {padding-right: 205px;}
.profiletopcoversize{padding-right: 205px;}
}
@media (max-width: 990px) {
body {padding-left: 0px;overflow-x: auto;}
.problackback{display:none !important}
}
@media (max-width: 600px) {
.timelineuserpropic{width: 85px;height: 85px;}
}
@media (max-width:480px){
.protopcov{min-height: 260px !important;}
.problackback{display:none !important}
.user-cover-reposition-w img#cover-image{height: 250px !important;}
}
</style>
<?php if($wo['loggedin'] == false) {  ?>
<style>
body {padding-left: 0px;}
.navbar-default {padding-right: 0px;}
.profiletopcoversize{padding-right: 0px;}

@media (min-width: 1200px){
body {padding-left: 0px;padding-right: 0px;}
.navbar-default {padding-right: 0px;}
}
@media (max-width: 990px) {
body {padding-left: 0px;overflow-x: auto;}
.hideinmenu {display: none;}
}
@media (max-width: 600px) {
.timelineuserpropic{width: 85px;height: 85px;}
}
</style>
<?php } ?>

<div class="modal fade" id="report_profile" role="dialog">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <h4 class="modal-title"><i class="fa fa-flag"></i> <?php echo $wo['lang']['report_user']; ?></h4>
         </div>
         <div class="modal-body">
            <textarea class="form-control" placeholder="Type text" dir="auto" rows="6" id="report-user-text-<?php echo $wo['user_profile']['id']; ?>"></textarea>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn  btn-main" id="report-user-button" onclick="Wo_ReportProfile(<?php echo $wo['user_profile']['id']; ?>,true)" >
            <i class="fa fa-paper-plane-o progress-icon" data-icon="paper-plane-o"></i>
             <?php echo $wo['lang']['send']; ?></button>
            <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $wo['lang']['cancel']; ?></button>
         </div>
      </div>
   </div>
</div>
<?php if ($wo['loggedin']): ?>
    <div class="modal fade" id="add_to_family" role="dialog">
       <div class="modal-dialog">
          <div class="modal-content">
             <div class="modal-header">
                <h4 class="modal-title"><i class="fa fa-group"></i> <?php echo $wo['lang']['family_member']; ?></h4>
             </div>
             <div class="add_to_family_alert">
                 
             </div>
             <div class="modal-body">
                <div class="col-md-3">
                <div class="family_mbr_avatar">
                    <img src="<?php echo $wo['user_profile']['avatar']; ?>" alt="<?php echo $wo['user_profile']['name']; ?> Picture" class="responsive-img">
                </div>
                </div>
                <div class="col-md-9">
                    <h4 class="family_mbr_name"><?php echo $wo['user_profile']['name']; ?></h4>
                    <?php if($wo['config']['user_lastseen'] == 1 && $wo['user_profile']['showlastseen'] != 0): ?>
                       <div class="user-lastseen">
                          <?php echo Wo_UserStatus($wo['user_profile']['user_id'],$wo['user_profile']['lastseen']); ?>
                       </div>
                    <?php endif; ?>
                    <div  class="add_as_cont">
                        <div class="col-md">
                            <label class="main">
                               <small><?php echo $wo['lang']['add_as']; ?>*</small>
                            </label>
                        </div>
                        <div class="col-md-">
                            <select class="form-control" name="family_list" id="family_list" title="Add as.">
                                <?php foreach ($wo['family'] as $key => $value): ?>
                                    <option value="<?php echo $key; ?>">
                                        <?php echo $wo['lang'][$value]; ?>
                                    </option>
                                <?php endforeach; ?>

                            </select>

                        </div>
                        <div class="clear"></div>
                    </div>
                    
                    
                </div>
                <div class="clear"></div>
             </div>
             <div class="modal-footer">
                <button type="button" class="btn btn-main" id="add_to_family_button" onclick="Wo_AddFamilyMember();">
                     <i class="fa fa-floppy-o progress-icon" data-icon="progress-icon"></i>
                     <?php echo $wo['lang']['save']; ?>
                </button>
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    <?php echo $wo['lang']['cancel']; ?>
                </button>
             </div>
          </div>
       </div>
    </div>
<?php endif; ?>
<div class="modal fade" id="delete_family_mbr_modal"  role="dialog" data-slide='true'>
 <div class="modal-dialog">
    <div class="modal-content">
       <div class="modal-header">
          <h4 class="modal-title"><i class="fa fa-exclamation-circle"></i> <?php echo $wo['lang']['important']; ?></h4>
       </div>
       <div class="modal-body">
          <p><?php echo $wo['lang']['confirm_remove_family_member']; ?></p>
       </div>
       <div class="modal-footer">
          <button id="delete_family_member_button"  type="button" class="btn btn-main" onclick="Wo_DeleteFamilyMember($('#delete_family_mbr_modal').attr('data-family-member-id'));">
          <i class="fa fa-trash-o progress-icon" data-icon="trash-o"></i> <?php echo $wo['lang']['delete']; ?>
          </button>
          <button type="button" class="btn btn-default" onclick="Wo_CloseModels();" data-dismiss="modal"><?php echo $wo['lang']['cancel']; ?></button>
       </div>
    </div>
 </div>
</div>
<div class="modal fade in" id="accept_family_mbr_modal" role="dialog">
  <div class="modal-dialog">
  
    <div class="modal-content">
      <p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 16px;">
        <i class="fa fa-check" aria-hidden="true" style="color: green;"></i>      
        <?php echo $wo['lang']['family_member_added']; ?>
      </p>
    </div>
    
  </div>
</div>
<!-- JS Timline functions -->
<script>

function Wo_ActivateFamilyMember(id = false,self = false,member = false){
    if (!id || !self || !member) {
        return false;
    }
    Wo_progressIconLoader($(self).find('i'));
    $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'family',s:'accept_member',id:id,type:member},
    })
    .done(function(data) {
        if (data.status == 200) {
            $("#accept_family_mbr_modal").modal('show');
            $('[data-family-member="'+id+'"]').slideUp(function(){
                    $(this).remove();
            })
            Wo_Delay(function(){
                $("#accept_family_mbr_modal").modal('hide');
            },1500);
        }
    })
    .fail(function() {
        console.log("error");
    })
    Wo_progressIconLoader($(self).find('i'));
}

function Wo_AcceptRelationRequest(id = false,member = false,type = false ,self = false){
    if (!member || !self || !type || !id) {
        return false;
    }
    Wo_progressIconLoader($(self));
    $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'family',s:'accept_relation',id:id,type:type,member:member},
    })
    .done(function(data) {
        if (data.status == 200) {
            window.location = data.url;
        }
    })
    .fail(function() {
        console.log("error");
    })
}

function Wo_DeleteRelationRequest(id = false,user = false,type = false,self = false){
    if (!self || !id || !user || !type) {
        return false;
    }
    Wo_progressIconLoader($(self).find('i'));
    $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'family',s:'delete_relation',id:id,user:user,type:type},
    })
    .done(function(data) {
        if (data.status == 200) {
            $("[data-relationship-request='"+id+"']").slideUp(function(){
                $(this).remove();
            })
        }
    })
    .fail(function() {
        console.log("error");
    })
    Wo_progressIconLoader($(self).find('i'));
}

function Wo_DeleteFamilyMember(id = false){
    if (!id) {
        return false;
    }
    Wo_progressIconLoader($("#delete_family_member_button"));
    $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'family',s:'delete_member',id:id},
    })
    .done(function(data) {
        if (data.status == 200) {
            $('[data-family-member="'+id+'"]').slideUp('slow',function(){
                    $(this).remove();
            })
            Wo_Delay(function(){
                $("#delete_family_mbr_modal").modal('hide');
            },1500);
        }
        Wo_progressIconLoader($("#delete_family_member_button"));
    })
    .fail(function() {
        console.log("error");
    })
    
}

function Wo_AddFamilyMember(){
    var member_type = $("#family_list").val();
    if (!member_type || member_type < 1 || member_type > 43) {
        return false;
    }
    Wo_progressIconLoader($("#add_to_family_button"));
    $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {
            f: 'family',
            s:'add_member',
            member_id:'<?php echo $wo['user_profile']['user_id']; ?>',
            type:member_type
        },
    })
    .done(function(data) {
        if (data.status == 200) {
            $('.add_to_family_alert').html('<div class="alert alert-success">' + data.message + '</div>');
            Wo_Delay(function(){
                $("#open_add_to_family_modal").slideUp(function(){
                    $(this).remove();
                    $("#add_to_family").modal('hide');
                })
            },1500);
            
        }
        else{
            $('.add_to_family_alert').html('<div class="alert alert-success">' + data.message + '</div>');
        }
        Wo_progressIconLoader($("#add_to_family_button"));
    })
    .fail(function() {
        console.log("error");
    })  
}

function Wo_ReportProfile(id = false,report = true){
    var report_text = $("#report-user-text-<?php echo $wo['user_profile']['id']; ?>").val();
    if (!id) {return false;}
    else if(report == true){
      if (!report_text) {return false;}  
    }
    Wo_progressIconLoader($("#report-user-button"));
    $.ajax({
        url: Wo_Ajax_Requests_File() + '?f=reports&s=report_user',
        type: 'POST',
        dataType: 'json',
        data: {text:report_text,user:id},
    })
    .done(function(data) {
        if(data.status == 200 && data.code == 0){
            $('#report_status').replaceWith('\
                <li id="report_status" class="list-group-item pointer" onclick="$(\'#report_profile\').modal(\'show\');">\
                    <img class="profile-icon" src="<?php echo Wo_GetIcon('flag-2'); ?>" alt="flag-2">\
                    <span><?php echo $wo['lang']['report_user']; ?></span>\
                </li>');
        }

        else if (data.status == 200 && data.code == 1) {
            $("#report-user-text-<?php echo $wo['user_profile']['id']; ?>").val('');
            $("#report_profile").modal('hide');
            $('#report_status').replaceWith('\
                <li id="report_status" class="list-group-item pointer" onclick="Wo_ReportProfile(<?php echo $wo['user_profile']['id']; ?>,false);">\
                    <img class="profile-icon" src="<?php echo Wo_GetIcon('flag-2'); ?>" alt="flag-2">\
                    <span><?php echo $wo['lang']['unreport']; ?></span>\
                </li>');
        }
        Wo_progressIconLoader($("#report-user-button"));
        
    })
    .fail(function() {
        console.log("error");
    })
}

function loadposts(user_id) {
  $.get(Wo_Ajax_Requests_File() + '?f=load_profile_posts', {user_id:user_id}, function(data) {
    $('.posts_load').html(data);
  });
}

var user_id = $('.profile').attr('data-id');
$(function () {
  user_id = $('.profile').attr('data-id');
  <?php 
  if (!empty($_GET['story'])) {
    ?>
    Wo_LoadStory('prof', $('[data-page=timeline]').attr('data-id'));
    <?php
  }
  ?>
  if($(window).width() > 600) {
    $(".user-avatar").hover(function () {
      $('.profile-avatar-changer').fadeIn(100);
    }, function () {
      $('.profile-avatar-changer').fadeOut(100);
    });
  }
  if($(window).width() > 600) {
    $(".user-cover").hover(function () {
      $('.profile-cover-changer').fadeIn(100);
    }, function () {
      $('.profile-cover-changer').fadeOut(100);
    });
  }
  
  $('form.profile-avatar-changer').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_user_avatar_picture',

    beforeSend: function () {
      $('.user-avatar-uploading-container, .user-avatar-uploading-progress').fadeIn(200);
    },
    success: function (data) {
      if(data.status == 200) {
        Wo_GetNewPosts();
        $('[id^=updateImage-<?php echo $wo['user_profile']['id']; ?>]').attr('data-target', '#ProfileImageModal-Stopped'); 
        $('[id^=updateImage-<?php echo $wo['user_profile']['id']; ?>]').attr('onclick', 'Wo_OpenProfilePicture("' + data.img_or + '");');
        $('[id^=updateImage-<?php echo $wo['user_profile']['id']; ?>]').attr("src", data.img);
		
		if($("ul[data-profile-completion]").length == 1) {
            if ($('#add-profile-avatar').length == 1) {
                window.location.reload();
            }
        }
		
      }
      $('.user-avatar-uploading-container,.user-avatar-uploading-progress').fadeOut(200);
    }
  });
  
  $('form.cover-position-form').ajaxForm({
        url:  Wo_Ajax_Requests_File() + '?f=re_cover',
        dataType:  'json', 
        beforeSend: function() {
            $('.user-reposition-dragable-container').hide();
            $('.user-repositioning-icons-container1').show();
            $('.user-repositioning-icons-container').html('<i class="fa fa-spinner fa-spin progress-icon" data-icon="spin"></i>').fadeIn('fast');
        },
        success: function(data) {
            if (data.status == 200) {
                $('.user-cover-reposition-w img').attr('src', data.url + '?time=' + Math.random()).on("load", function () {
                    $('.when-edit').hide();
                    $('.when-notedit').show();
                    $('.user-repositioning-icons-container1').fadeOut('fast');
                    $('.user-repositioning-icons-container').fadeOut('fast').html('');
                    $('.user-cover-reposition-w').show();
                    $('.user-reposition-container').hide().find('img').css('top', 0);
                    $('.cover-resize-buttons').hide();
                    $('.default-buttons').show();
                    $('input.cover-position').val(0);
                    $('.user-reposition-container img').draggable('destroy').css('cursor','default');
                    window.location.reload();
                });
            }
        }
    });
  $('.profile-cover-changer').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_user_cover_picture',

    beforeSend: function () {
      $('.user-cover-uploading-container,.user-cover-uploading-progress').fadeIn(200);
    },
    success: function (data) {
      if(data.status == 200) {
        Wo_GetNewPosts();
        $('[id^=cover-image]').attr('data-target', '#ProfileCoverImageModal-Stopped');      
        $('[id^=cover-image]').attr('onclick', 'Wo_OpenProfileCover("' + data.cover_or + '");');
        $('[id^=cover-image]').attr("src", data.img);
        $('#full-image').attr("src", data.cover_full);
        $('#full-input-image').val(data.cover_full);
        $('#cover-input-image').val(data.cover_or);
        Wo_StartRepositioner();
      }
      $('.user-cover-uploading-container,.user-cover-uploading-progress').fadeOut(200);
    }
  });
});

function Wo_GetFollowing(user_id) {
  Wo_progressIconLoader($('#sidebar-following-list-container').find('span'));
  $.get(Wo_Ajax_Requests_File(), {
    f: 'get_following_users',
    user_id: user_id
  }, function (data) {
    if(data.status == 200) {
      $('.sidebar-following-users-container').html(data.html);
    }
    Wo_progressIconLoader($('#sidebar-following-list-container').find('span'));
  });
}

function Wo_GetFollowers(user_id) {
  Wo_progressIconLoader($('#sidebar-followers-list-container').find('span'));
  $.get(Wo_Ajax_Requests_File(), {
    f: 'get_followers_users',
    user_id: user_id
  }, function (data) {
    if(data.status == 200) {
      $('.sidebar-followers-users-container').html(data.html);
    }
    Wo_progressIconLoader($('#sidebar-followers-list-container').find('span'));
  });
}

function Wo_GetLikes(user_id) {
  Wo_progressIconLoader($('#sidebar-pages-list-container').find('span'));
  $.get(Wo_Ajax_Requests_File(), {
    f: 'pages',
    s: 'get_likes',
    user_id: user_id
  }, function (data) {
    if(data.status == 200) {
      $('.sidebar-likes-container').html(data.html);
    }
    Wo_progressIconLoader($('#sidebar-pages-list-container').find('span'));
  });
}

function Wo_GetMoreFollowing(user_id) {
  Wo_progressIconLoader($('.load-more').find('button'));
  after_last_id = $('.user-data:last').attr('data-user-id');
  $.get(Wo_Ajax_Requests_File(), {
    f: 'get_more_following',
    user_id: user_id,
    after_last_id: after_last_id
  }, function (data) {
    if(data.status == 200) {
      if(data.html.length == 0) {
        $('.load-more').find('button').text("<?php echo $wo['lang']['no_more_users_to_show']; ?>");
      } else {
        $('#following-list').append(data.html);
      }
    }
    Wo_progressIconLoader($('.load-more').find('button'));
  });
}

function Wo_GetMoreUserLikes(user_id) {
  Wo_progressIconLoader($('.load-more').find('button'));
  after_last_id = $('.user-data:last').attr('data-page-id');
  $.get(Wo_Ajax_Requests_File(), {
    f: 'pages',
    s: 'get_more_likes',
    user_id: user_id,
    after_last_id: after_last_id
  }, function (data) {
    if(data.status == 200) {
      if(data.html.length == 0) {
        $('.load-more').find('button').text("<?php echo $wo['lang']['no_more_pages']; ?>");
      } else {
        $('#likes-list').append(data.html);
      }
    }
    Wo_progressIconLoader($('.load-more').find('button'));
  });
}

function Wo_GetMoreFollowers(user_id) {
  Wo_progressIconLoader($('.load-more').find('button'));
  after_last_id = $('.user-data:last').attr('data-user-id');
  $.get(Wo_Ajax_Requests_File(), {
    f: 'get_more_followers',
    user_id: user_id,
    after_last_id: after_last_id
  }, function (data) {
    if(data.status == 200) {
      if(data.html.length == 0) {
        $('.load-more').find('button').text("<?php echo $wo['lang']['no_more_users_to_show']; ?>");
      } else {
        $('#followers-list').append(data.html);
      }
    }
    Wo_progressIconLoader($('.load-more').find('button'));
  });
}

function Wo_UpdateProfileAvatar() {
  $("form.profile-avatar-changer").submit();
}

function Wo_UpdateProfileCover() {
  $("form.profile-cover-changer").submit();
}

function Wo_SetCookieAlert() {
  $.get(Wo_Ajax_Requests_File(), {
    f: 'set_admin_alert_cookie'
  });
}

function Wo_OpenProfileCover(image) {
    $.post(Wo_Ajax_Requests_File() + '?f=get_user_profile_cover_image_post', {
      image:image
    }, function (data) {
        if (data.status == 200) {
            Wo_OpenLightBox(data.post_id);
        } else {
            $('[id^=cover-image]').attr('data-target', '#ProfileCoverImageModal');
            $('[id^=cover-image]').attr('data-toggle', 'modal');
            $('#ProfileCoverImageModal').modal('show');
        }
    });
}

function Wo_OpenProfilePicture(image) {
    $.post(Wo_Ajax_Requests_File() + '?f=get_user_profile_image_post', {
      image:image
    }, function (data) {
        if (data.status == 200) {
            Wo_OpenLightBox(data.post_id);
        } else {
            $('[id^=updateImage-' + user_id + ']').attr('data-target', '#ProfileImageModal-' + user_id);
            $('[id^=updateImage-' + user_id + ']').attr('data-toggle', 'modal');
            $('#ProfileImageModal-' + user_id).modal('show');
        }
    });
}

$(function(){

    var url = window.location.pathname, 
        urlRegExp = new RegExp(url.replace(/\/$/,'') + "$"); // create regexp to match current url pathname and remove trailing slash if present as it could collide with the link in navigation in case trailing slash wasn't present there
        // now grab every link from the navigation
        $('#profilenav a').each(function(){
            // and test its normalized href against the url pathname regexp
            if(urlRegExp.test(this.href.replace(/\/$/,''))){
                $(this).addClass('menuactive');
            }
        });

});

$(function(){

    var url = window.location.pathname, 
        urlRegExp = new RegExp(url.replace(/\/$/,'') + "$"); // create regexp to match current url pathname and remove trailing slash if present as it could collide with the link in navigation in case trailing slash wasn't present there
        // now grab every link from the navigation
        $('#profilenav-mobile a').each(function(){
            // and test its normalized href against the url pathname regexp
            if(urlRegExp.test(this.href.replace(/\/$/,''))){
                $(this).addClass('menuactive');
            }
        });

});
</script>

<style>
.post-youtube iframe {
    overflow: hidden !important; height: 360px !important;
}
</style>