<?php if (Wo_FriendPrivacy($wo['user_profile']['id'],$wo['user_profile']['friend_privacy'])): ?>
<ul class="list-group" id="sidebar-followers-list-container">
   <li class="list-group-item text-muted " contenteditable="false">
     <i class="zmdi zmdi-accounts-alt" style="font-size: 20px;margin: -3px 5px 0px 0px;"></i> <?php echo $wo['lang']['friends_btn'];?> (<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=followers');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=followers"><?php echo $wo['user_profile']['details']['following_count'];?></a>) 
      <span onclick="Wo_GetFollowers(<?php echo $wo['user_profile']['user_id']?>);" class="<?php echo Wo_RightToLeft('pull-right');?> refresh">
      <i class="fa fa-repeat progress-icon" data-icon="repeat"></i>
      </span>
   </li>
   <li>
      <div class="sidebar-followers-users-container">
          <?php 
          foreach (Wo_GetFollowing($wo['user_profile']['user_id'], 'sidebar', 9, 0, array('in' => 'profile_sidebar', 'following_data' => $wo['user_profile']['following_data'])) as $wo['UsersList']) {
            $wo['UsersList']['user_name'] = mb_substr($wo['UsersList']['name'], 0, 10, "utf-8");
            echo Wo_LoadPage('sidebar/profile-sidebar-user-list');
          }
          ?>
      </div>
   </li>
   <li>
      <div class="clear"></div>
   </li>
</ul>
<?php endif; ?>