<ul class="list-group" id="sidebar-pages-list-container">
   <li class="list-group-item text-muted " contenteditable="false">
   <a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=groups');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=groups">
      <i class="zmdi zmdi-group-work" style="font-size: 20px;margin: -3px 5px 0px 0px;"></i><?php echo $wo['lang']['groups'];?></a> (<?php echo $wo['user_profile']['details']['groups_count'];?>)
   </li>
   <li>
      <div class="sidebar-groups-container">
          <?php 
          foreach (Wo_GetUsersGroups($wo['user_profile']['user_id'], 12, array('in' => 'profile_sidebar', 'groups_data' => $wo['user_profile']['groups_data'])) as $wo['GroupList']) {
            $wo['GroupList']['name'] = mb_substr($wo['GroupList']['name'], 0, 10, "utf-8");
            echo Wo_LoadPage('sidebar/sidebar-groups-list');
          }
          ?>
      </div>
   </li>
   <li>
      <div class="clear"></div>
   </li>
</ul>