<ul class="list-group" id="sidebar-pages-list-container">
   <li class="list-group-item text-muted" contenteditable="false">
   <a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=likes');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=likes">
      <i class="zmdi zmdi-thumb-up" style="font-size: 20px;margin: -3px 5px 0px 0px;"></i><?php echo $wo['lang']['likes'];?></a> (<?php echo $wo['user_profile']['details']['likes_count'];?>) 
      <span onclick="Wo_GetLikes(<?php echo $wo['user_profile']['user_id']?>);" class="<?php echo Wo_RightToLeft('pull-right');?> refresh">
      <i class="fa fa-repeat progress-icon" data-icon="repeat"></i>
      </span>
   </li>
   <li>
      <div class="sidebar-likes-container">
          <?php 
          foreach (Wo_GetLikes($wo['user_profile']['user_id'], 'profile', 12, array('in' => 'profile_sidebar', 'likes_data' => $wo['user_profile']['likes_data'])) as $wo['PageList']) {
            $wo['PageList']['user_name'] = mb_substr($wo['PageList']['name'], 0, 10, "utf-8");
            echo Wo_LoadPage('sidebar/sidebar-page-list');
          }
          ?>
      </div>
   </li>
   <li>
      <div class="clear"></div>
   </li>
</ul>