<div class="list-group">
   <div class="list-group-item"><i class="fa fa-fw fa-paint-brush"></i> <?php echo $wo['lang']['design'];?> <?php if(Wo_IsAdmin() === true) { ?><a href="<?php echo $wo['setting']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['setting']['username'] ?>">(<?php echo $wo['setting']['name'];?>)</a><?php } ?></div>
   <div class="setting-well">
   <form  method="post" class="form-horizontal setting-profile-form" enctype="multipart/form-data">
      <fieldset>
         <div class="setting-profile-alert setting-update-alert"></div>
          <!-- Text input-->
         <div class="form-group">
            <label class="col-md-2" for="background_image"><?php echo $wo['lang']['background']; ?></label>  
            <div class="col-md-7">
               <span class="btn btn-default btn-file">
                     <i class="fa fa-picture-o "></i>
                     <input type="file" id="background_image"  accept="image/*" name="background_image">
               </span>
            </div>
         </div>
         <div class="form-group avatar-read" id="photo-form">
               <label class="col-md-2"></label>  
               <div class="col-md-7">
                  <input type="text" class="form-control input-md" readonly>
               </div>
         </div>
                  <?php if (!empty($wo['setting']['background_image'])) { ?>
         <div class="form-group">
            <?php 
            $selected_my_background   = ($wo['setting']['background_image_status'] == '1')   ? ' checked' : '';
            $selected_defualt_background = ($wo['setting']['background_image_status'] == '0')   ? ' checked' : '';
            ?>
            <label class="col-md-2" for="background_image_status"><?php echo $wo['lang']['theme']; ?></label>
            <div class="col-md-5"> 
               <label class="radio-inline" for="background_image_status-0">
               <input type="radio" name="background_image_status" id="background_image_status-0" value="defualt" <?php echo $selected_defualt_background; ?>>
               <?php echo $wo['lang']['deafult']; ?>
               </label> 
               <label class="radio-inline" for="background_image_status-1">
               <input type="radio" name="background_image_status" id="background_image_status-1" value="my_background" <?php echo $selected_my_background; ?>>
               <?php echo $wo['lang']['my_background']; ?>
               </label>
            </div>
         </div>
         <?php }?>
         <?php if ($wo['config']['css_upload'] == 1) { ?>
         <div class="form-group">
            <label class="col-md-2" for="css_file"><?php echo $wo['lang']['css_file'];?></label>  
            <div class="col-md-7">
                <span class="btn btn-default btn-file">
                     <i class="fa fa-file-o "></i>
                     <input type="file" id="css_file" accept="text/css" name="css_file">
               </span>
               <span class="help-block"><?php echo $wo['lang']['css_file_info'];?></span>
            </div>
         </div>
         <div class="form-group css_file-read" id="photo-form">
               <label class="col-md-2"></label>  
               <div class="col-md-7">
                  <input type="text" class="form-control input-md" readonly>
               </div>
         </div>
         <?php if (!empty($wo['setting']['css_file']) && file_exists($wo['setting']['css_file'])) { ?>
         <div class="form-group">
            <?php 
            $selected_my_css   = (!empty($wo['setting']['css_file']) && file_exists($wo['setting']['css_file'])) ? ' checked' : '';
            $selected_defualt_css = (!empty($wo['setting']['css_file']) && file_exists($wo['setting']['css_file']))   ? ' checked' : '';
            ?>
            <label class="col-md-2" for="css_status"><?php echo $wo['lang']['design'];?></label>
            <div class="col-md-5"> 
               <label class="radio-inline" for="css_status-0">
               <input type="radio" name="css_status" id="css_status-0" value="1" <?php echo $selected_defualt_css; ?>>
               <?php echo $wo['lang']['css_status_default'];?>
               </label> 
               <label class="radio-inline" for="css_status-1">
               <input type="radio" name="css_status" id="css_status-1" value="2" <?php echo $selected_my_css; ?>>
               <?php echo $wo['lang']['css_status_my'];?>
               </label>
            </div>
         </div>
         <?php } ?>
         <?php } ?>
         <hr>
         <div class="form-group last-btn">
            <label class="col-md-2"></label>  
            <div class="col-sm-3">
               <button type="submit" class="mdbtn wabe btn btn-main">
               <i class="fa fa-floppy-o progress-icon" data-icon="floppy-o"></i> <?php echo $wo['lang']['save']; ?>
               </button>
            </div>
         </div>
         <input type="hidden" name="user_id" id="user-id" value="<?php echo $wo['setting']['user_id'];?>">
         <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
      </fieldset>
   </form>
</div>
</div>

<script type="text/javascript">
$(function() {
  $("#background_image").change(function () {
         var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
         $(".avatar-read input").val(filename);
         $(".avatar-read").slideDown(200);
    });
  $("#css_file").change(function () {
         var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
         $(".css_file-read input").val(filename);
         $(".css_file-read").slideDown(200);
    });
  $('form.setting-profile-form').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_design_setting',
    beforeSend: function() {
      Wo_progressIconLoader($('form.setting-profile-form').find('button'));
    },
    success: function(data) {
      if (data.status == 200) {
        scrollToTop();
        $('.setting-profile-alert').html('<div class="alert alert-success">' + data.message + '</div>');
        $('.alert-success').fadeIn('fast', function() {
          $(this).delay(2500).slideUp(500, function() {
            $(this).remove();
          });
        });
      } 
      Wo_progressIconLoader($('form.setting-profile-form').find('button'));
    }
  });
  $("#background_image").on('change', function() {
         $("#background_image_status-1").attr("checked", true);
  });
});
</script>