<?php echo Wo_LoadPage('welcome/welcome-header');?>
<div class="wrapper">
 <?php echo Wo_LoadPage('welcome/welcome-header-logo');?>
  <form class="login" id="forgot-form" method="post">
    <p class="title"><?php echo $wo['lang']['forgot_your_password']; ?></p>
    <input name="recoveremail" id="recoveremail" type="text" placeholder="<?php echo $wo['lang']['email'];?>" autofocus/>
    <i class="zmdi zmdi-email"></i>
    <button>
    <i class="spinner"></i>
    <span class="state"><i class="zmdi zmdi-refresh zmdi-hc-fw"></i> <?php echo $wo['lang']['recover_password'];?></span>
    </button>
  </form>
  <?php echo Wo_LoadPage('footer/welcome-b');?>
</div>

<script>
var working = false;
var $this = $('#forgot-form');
var $state = $this.find('button > .state');
var forgot_button_text = "<i class='zmdi zmdi-refresh zmdi-hc-fw'></i> <?php echo $wo['lang']['recover_password']?>";
$(function() {
  Wo_SetTimer();
  $this.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=recover',
    beforeSend: function() {
      working = true;
      $this.addClass('loading');
      $state.html('<?php echo $wo['lang']['please_wait'] ?>');
    },
    success: function(data) {
      if (data.status == 200) {
        $this.addClass('ok');
        $state.html('<?php echo $wo['lang']['email_sent'] ?>');
        setTimeout(function () {
          $this.removeClass('ok loading');
          $state.html(forgot_button_text);
        }, 5000);
      } else {
        $state.html(forgot_button_text);
        $this.removeClass('ok loading', function () {
         $state.html(data.errors);
        });
      }
      working = false;
    }
  });
});
</script>
